//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectivosService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class colectivo_beacon
    {
        public long id { get; set; }
        public long id_colectivo { get; set; }
        public long id_beacon { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    
        public virtual beacon beacon { get; set; }
        public virtual colectivo colectivo { get; set; }
    }
}
