//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectivosService.DataObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TP_SeminarioEntities : DbContext
    {
        public TP_SeminarioEntities()
            : base("name=TP_SeminarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beacon> beacon { get; set; }
        public virtual DbSet<colectivo> colectivo { get; set; }
        public virtual DbSet<colectivo_beacon> colectivo_beacon { get; set; }
        public virtual DbSet<parada> parada { get; set; }
        public virtual DbSet<pasajero> pasajero { get; set; }
        public virtual DbSet<reclamo> reclamo { get; set; }
        public virtual DbSet<recorrido> recorrido { get; set; }
        public virtual DbSet<recorrido_parada> recorrido_parada { get; set; }
        public virtual DbSet<viaje_colectivo> viaje_colectivo { get; set; }
        public virtual DbSet<viaje_pasajero> viaje_pasajero { get; set; }
    }
}
