//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectivosService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclamo
    {
        public long id { get; set; }
        public long id_pasajero { get; set; }
        public string detalle { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual pasajero pasajero { get; set; }
    }
}
