//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectivosService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class recorrido_parada
    {
        public long id { get; set; }
        public long id_recorrido { get; set; }
        public long id_parada { get; set; }
        public int estado { get; set; }
    
        public virtual parada parada { get; set; }
        public virtual recorrido recorrido { get; set; }
    }
}
