//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectivosService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje_pasajero
    {
        public long id { get; set; }
        public long id_viaje_colectivo { get; set; }
        public long id_pasajero { get; set; }
        public long id_parada { get; set; }
        public Nullable<int> latitud { get; set; }
        public Nullable<int> longitud { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    
        public virtual parada parada { get; set; }
        public virtual pasajero pasajero { get; set; }
        public virtual viaje_colectivo viaje_colectivo { get; set; }
    }
}
